<!-- header.inc -->
<header class="header-section">
  <div class="header">
    <nav class="headerlogo">
      <a href="index.php" class="logo">
        <img src="images/logo.png" class="logo-image" alt="Company Logo">
        <div class="logo-text">
          <span class="logo-main">Shield</span>
          <span class="logo-sub">Cyber Security</span>
        </div>
      </a>

      <ul class="menu">
        <li><a href="index.php">Home</a></li>
        <li><a href="jobs.php">Job Information</a></li>
        <li><a href="apply.php">Job Application</a></li>
        <li><a href="about.php">About Us</a></li>
        <li><a href="login.php">Management</a></li>
        <li><a href="enhancements.php">Enhancements</a></li>  
      </ul>
    </nav>
  </div>
  <div class="welcome">
      <h1>Welcome to Shield Cyber Security</h1>
      <p>Passionate about the strongest protection for everyone.</p>
  </div>    
</header>
